name: builder

on: push

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build app
        uses: boschrexroth/ctrlx-build-snap-action@v1
        with: 
          architacture: amd64

      #Decide
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v0.0.1
<<<<<<< HEAD
          files: '*.snap'
=======
          files: '*.snap'
>>>>>>> eee70a23130457ed6258388086c26c9caee51a40
