name: builder

on: push

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build app
        uses: jmohren/ctrlx-build-snap-action@v0.1.2
        with: 
          architacture: amd64

      #Decide
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v0.0.1
          files: '*.snap'
