name: builder

on: push

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build app
        uses: jmohren/ctrlx-build-app-action@v0.0.15
        with: 
          app-name: datalayerclient

      #Decide
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: jmohren
          author_email: johannes.mohren@rwth-aachen.de
          message: 'app file'
          add: '*.app'

      #Decide
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v0.0.1
          files: datalayerclient.app
